#! /usr/bin/env python3

# display the header
print("Change Calculator")
print()


# get input from the user
q = 25
d = 10
n = 5
p = 1

choice = "y"


while choice.lower() == "y":
    numberofcents = int(input("Enter the number of cents (0-99):\t"))


    qs = numberofcents // q

    dstarting = numberofcents - (q * qs)
    ds = dstarting // d
    nstarting = dstarting - (ds * 10)
    ns = nstarting // n
    pstarting = nstarting - (ns * 5)
    ps = pstarting // p



    print("Quarters:\t\t\t\t " + str(qs))
    print("Dimes:\t\t\t\t\t " + str(ds))
    print("Nickels:\t\t\t\t " + str(ns))
    print("Pennies:\t\t\t\t " + str(ps))

    choice = input("Continue (y/n)?:  ")
    print()

